services:
    php-fpm:
        container_name: text-magic-fpm
        build:
            context: ./infra/php
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./project:/var/www/html
        networks:
            - text-magic-network

    nginx:
        container_name: text-magic-nginx
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./project:/var/www/html
            - ./infra/nginx/:/etc/nginx/conf.d
        depends_on:
            - php-fpm
        networks:
            - text-magic-network

    postgres:
        container_name: text-magic-postgres
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: postgres12
        ports:
            - "5432:5432"
        networks:
            - text-magic-network

networks:
    text-magic-network:
        driver: bridge
